In [207]:
from pathlib import Path
import pandas as pd
import numpy as np

In [208]:
PROJECT_ROOT = Path.cwd().parent

RAW_DATA_DIR = PROJECT_ROOT / "data" / "raw"
INTERIM_DATA_DIR = PROJECT_ROOT / "data" / "interim"
PROCESSED_DATA_DIR = PROJECT_ROOT / "data" / "processed"

print("Project root:", PROJECT_ROOT)
print("Raw data:", RAW_DATA_DIR)
print("Interim data:", INTERIM_DATA_DIR)
print("Processed data:", PROCESSED_DATA_DIR)

Project root: /Users/priyashekhawat/Desktop/ree/project/cafescope
Raw data: /Users/priyashekhawat/Desktop/ree/project/cafescope/data/raw
Interim data: /Users/priyashekhawat/Desktop/ree/project/cafescope/data/interim
Processed data: /Users/priyashekhawat/Desktop/ree/project/cafescope/data/processed

In [209]:
list(RAW_DATA_DIR.iterdir())

[PosixPath('/Users/priyashekhawat/Desktop/ree/project/cafescope/data/raw/zom_jaipur.csv'),
 PosixPath('/Users/priyashekhawat/Desktop/ree/project/cafescope/data/raw/zom_real.csv'),
 PosixPath('/Users/priyashekhawat/Desktop/ree/project/cafescope/data/raw/README.md'),
 PosixPath('/Users/priyashekhawat/Desktop/ree/project/cafescope/data/raw/useless.xlsx')]

In [210]:
DATA_PATH = RAW_DATA_DIR / "zom_jaipur.csv"

df = pd.read_csv(DATA_PATH)

df.head()

,Name,Url,Location,din_rev,del_rev,category,Cuisine_offered,cost_for_two,is_vegeterian,is_bar_available,home_delivery,offers_dining,avg_din_rate,avg_del_rate
0,1117,https://www.zomato.com/jaipur/1117-jagatpura,Jagatpura,137 Dining Reviews,"3,418 Delivery Reviews",Casual Dining,"North Indian, Fast Food",500,no,no,yes,yes,3.4,3.7
1,Feb-20,https://www.zomato.com/jaipur/feb-20-mansarovar,Mansarovar,30 Dining Reviews,231 Delivery Reviews,Quick Bites,Fast Food,300,yes,no,yes,yes,3.4,3.8
2,#Jaipur Darbar,https://www.zomato.com/jaipur/jaipur-darbar-to...,Pratap Nagar,18 Dining Reviews,126 Delivery Reviews,Quick Bites,"North Indian, Mughlai, Chinese, Fast Food",500,no,no,yes,yes,3.5,3.8
3,#Underground Restro & Bar,https://www.zomato.com/jaipur/underground-rest...,Vidhyadhar Nagar,13 Dining Reviews,Does not offer Delivery,Bar,"North Indian, Mughlai",700,no,yes,no,yes,3.1,NaN
4,0141 Resturant,https://www.zomato.com/jaipur/0141-resturant-j...,Jagatpura,Not enough Dining Reviews,Does not offer Delivery,Quick Bites,North Indian,350,no,no,no,yes,NaN,NaN

In [211]:
df.shape

(4727, 14)

In [212]:
df.columns.tolist()

['Name',
 'Url',
 'Location',
 'din_rev',
 'del_rev',
 'category',
 'Cuisine_offered',
 'cost_for_two',
 'is_vegeterian',
 'is_bar_available',
 'home_delivery',
 'offers_dining',
 'avg_din_rate',
 'avg_del_rate']

In [213]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4727 entries, 0 to 4726
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Name              4727 non-null   str
 1   Url               4727 non-null   str
 2   Location          4727 non-null   str
 3   din_rev           4727 non-null   str
 4   del_rev           4727 non-null   str
 5   category          3796 non-null   str
 6   Cuisine_offered   4726 non-null   str
 7   cost_for_two      4727 non-null   str
 8   is_vegeterian     4727 non-null   str
 9   is_bar_available  4727 non-null   str
 10  home_delivery     4727 non-null   str
 11  offers_dining     4727 non-null   str
 12  avg_din_rate      2771 non-null   float64
 13  avg_del_rate      2287 non-null   float64
dtypes: float64(2), str(12)
memory usage: 517.1 KB

In [214]:
df.isna().sum()

Name                   0
Url                    0
Location               0
din_rev                0
del_rev                0
category             931
Cuisine_offered        1
cost_for_two           0
is_vegeterian          0
is_bar_available       0
home_delivery          0
offers_dining          0
avg_din_rate        1956
avg_del_rate        2440
dtype: int64

In [215]:
df.nunique()

Name                4237
Url                 4727
Location              48
din_rev              532
del_rev             1154
category              69
Cuisine_offered     1064
cost_for_two          49
is_vegeterian          2
is_bar_available       2
home_delivery          2
offers_dining          2
avg_din_rate          30
avg_del_rate          29
dtype: int64

In [216]:
df.duplicated().sum()

np.int64(0)

In [217]:
df["Name"].duplicated().sum()

np.int64(490)

In [218]:
df["category"].unique()

<StringArray>
[                'Casual Dining ',                   'Quick Bites ',
                           'Bar ',                              nan,
                   'Fine Dining ',                          'CAF� ',
            'Casual Dining, Bar ',                   'Lounge, Pub ',
                        'Lounge ',                        'Bakery ',
          'CAF�, Dessert Parlor ',                         'Dhaba ',
                    'Food Truck ',                 'Beverage Shop ',
           'Bakery, Quick Bites ',                  'Lounge, CAF� ',
            'Sweet Shop, Bakery ',       'Sweet Shop, Quick Bites ',
                    'Bhojanalya ',                    'Sweet Shop ',
    'Beverage Shop, Quick Bites ',                     'Paan Shop ',
                          'Mess ',                    'Food Court ',
                         'Kiosk ',                'Dessert Parlor ',
        'Bakery, Dessert Parlor ',         'Beverage Shop, Bakery ',
     'Sweet Shop, Casual Dining ',           'CAF�, Casual Dining ',
    'Sweet Shop, Dessert Parlor ',   'Dessert Parlor, Quick Bites ',
      'Quick Bites, Quick Bites ', 'Dessert Parlor, Beverage Shop ',
                     'Bar, Club ',           'Quick Bites, Bakery ',
       'Quick Bites, Sweet Shop ',            'Bar, Casual Dining ',
                  'CAF�, Bakery ',             'CAF�, Quick Bites ',
    'Quick Bites, Beverage Shop ',                 'Confectionery ',
   'Quick Bites, Dessert Parlor ',                          'Club ',
                   'Lounge, Bar ',           'Casual Dining, CAF� ',
                   'Bar, Lounge ',    'Quick Bites, Casual Dining ',
         'Casual Dining, Lounge ',                  'Bakery, CAF� ',
                     'Cafeteria ',      'Beverage Shop, Juice Bar ',
      'Quick Bites, Fine Dining ',    'Dessert Parlor, Food Court ',
         'Lounge, Casual Dining ',          'Kiosk, Confectionery ',
                     'Meat Shop ',        'Quick Bites, Meat Shop ',
       'Food Court, Quick Bites ',      'Beverage Shop, Fast Food ',
     'Casual Dining, Sweet Shop ', 'Beverage Shop, Dessert Parlor ',
             'Quick Bites, CAF� ',        'Dessert Parlor, Bakery ',
        'Food Court, Sweet Shop ',  'Beverage Shop, Beverage Shop ',
                    'CAF�, CAF� ',  'Casual Dining, Casual Dining ',
       'Quick Bites, Food Court ',  'Beverage Shop, Casual Dining ']
Length: 70, dtype: str

In [219]:
df.loc[df["category"].str.contains("CAF", case=False , na=False), "Name"].head(20)

9                               11MG
31                           8 Fumes
42                  A2G All Together
85                           After 8
101                       Ahimsagram
144    Amazing Arena Sports & Lounge
183          Anjum - Fairmont Jaipur
208                  Any Time Coffee
237                         Aromocha
239                         Art Cafe
260                     August House
294                Between The Brews
370                    Bistro Quaint
377                      Black Maple
387       Blue Tokai Coffee Roasters
390            Bnc - The Coffee Shop
401                    Bombaye House
402                           Bonana
427                      Brown Bites
428                      Brown Bites
Name: Name, dtype: str

In [220]:
cafe_df=df.loc[df["category"].str.contains("CAF", case=False , na=False)].copy()
len(cafe_df)

238

In [221]:
cafe_df.head()

,Name,Url,Location,din_rev,del_rev,category,Cuisine_offered,cost_for_two,is_vegeterian,is_bar_available,home_delivery,offers_dining,avg_din_rate,avg_del_rate
9,11MG,https://www.zomato.com/jaipur/11mg-mansarovar,Mansarovar,135 Dining Reviews,837 Delivery Reviews,CAF�,Cafe,400,yes,no,yes,yes,3.8,3.9
31,8 Fumes,https://www.zomato.com/jaipur/8-fumes-mansarovar,Mansarovar,8 Dining Reviews,Does not offer Delivery,CAF�,"Cafe, Fast Food",400,yes,no,no,yes,2.8,NaN
42,A2G All Together,https://www.zomato.com/jaipur/a2g-all-together...,Lal Kothi,496 Dining Reviews,"1,089 Delivery Reviews","CAF�, Dessert Parlor","Cafe, Desserts, North Indian, Chinese, Frozen ...",600,yes,no,yes,yes,4.0,3.6
85,After 8,https://www.zomato.com/jaipur/after-8-sansar-c...,Sansar Chandra Road,Not enough Dining Reviews,Does not offer Delivery,"Lounge, CAF�","Finger Food, Continental, Beverages","1,500",no,yes,no,yes,NaN,NaN
101,Ahimsagram,https://www.zomato.com/jaipur/ahimsagram-1-ton...,Sanganer,7 Dining Reviews,Not enough Delivery Reviews,CAF�,Healthy Food,400,no,no,yes,yes,3.6,NaN

In [222]:
cafe_df.info()

<class 'pandas.DataFrame'>
Index: 238 entries, 9 to 4725
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Name              238 non-null    str
 1   Url               238 non-null    str
 2   Location          238 non-null    str
 3   din_rev           238 non-null    str
 4   del_rev           238 non-null    str
 5   category          238 non-null    str
 6   Cuisine_offered   238 non-null    str
 7   cost_for_two      238 non-null    str
 8   is_vegeterian     238 non-null    str
 9   is_bar_available  238 non-null    str
 10  home_delivery     238 non-null    str
 11  offers_dining     238 non-null    str
 12  avg_din_rate      221 non-null    float64
 13  avg_del_rate      121 non-null    float64
dtypes: float64(2), str(12)
memory usage: 27.9 KB

In [223]:
cafe_df.isna().sum()

Name                  0
Url                   0
Location              0
din_rev               0
del_rev               0
category              0
Cuisine_offered       0
cost_for_two          0
is_vegeterian         0
is_bar_available      0
home_delivery         0
offers_dining         0
avg_din_rate         17
avg_del_rate        117
dtype: int64

In [224]:
cafe_df.shape

(238, 14)

In [225]:
cafe_df.describe(include="all").T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
Name,238,222,Cafe Coffee Day,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Url,238,238,https://www.zomato.com/jaipur/11mg-mansarovar,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Location,238,37,Malviya Nagar,38,NaN,NaN,NaN,NaN,NaN,NaN,NaN
din_rev,238,158,Not enough Dining Reviews,13,NaN,NaN,NaN,NaN,NaN,NaN,NaN
del_rev,238,118,Not enough Delivery Reviews,58,NaN,NaN,NaN,NaN,NaN,NaN,NaN
category,238,11,CAF�,189,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Cuisine_offered,238,120,Cafe,34,NaN,NaN,NaN,NaN,NaN,NaN,NaN
cost_for_two,238,24,400,50,NaN,NaN,NaN,NaN,NaN,NaN,NaN
is_vegeterian,238,2,yes,138,NaN,NaN,NaN,NaN,NaN,NaN,NaN
is_bar_available,238,2,no,233,NaN,NaN,NaN,NaN,NaN,NaN,NaN
home_delivery,238,2,yes,181,NaN,NaN,NaN,NaN,NaN,NaN,NaN
offers_dining,238,2,yes,234,NaN,NaN,NaN,NaN,NaN,NaN,NaN
avg_din_rate,221.0,NaN,NaN,NaN,3.647511,0.518263,2.2,3.3,3.7,4.0,4.9
avg_del_rate,121.0,NaN,NaN,NaN,3.777686,0.407531,2.2,3.5,3.8,4.1,4.8

In [226]:
df['Cuisine_offered'].unique()

<StringArray>
[                                   'North Indian, Fast Food',
                                                  'Fast Food',
                  'North Indian, Mughlai, Chinese, Fast Food',
                                      'North Indian, Mughlai',
                                               'North Indian',
                                     'North Indian, European',
                         'South Indian, Beverages, Fast Food',
                             'South Indian, Chinese, Italian',
                          'North Indian, Mughlai, Rajasthani',
                                                       'Cafe',
 ...
                              'Beverages, Desserts, Sandwich',
                             'North Indian, Mexican, Italian',
                         'Fast Food, Momos, Pizza, Beverages',
                                 'Hot dogs, Momos, Fast Food',
                     'Burger, Fast Food, Beverages, Desserts',
                                             'Biryani, Kebab',
 'North Indian, Chinese, American, Continental, South Indian',
                              'Afghan, Chinese, North Indian',
                             'Arabian, Turkish, North Indian',
                            'Cafe, Italian, Beverages, Asian']
Length: 1065, dtype: str

In [227]:
cuisine_lists=(
    df['Cuisine_offered']
    .fillna("")
    .str.split(",")
    .apply( lambda x: [c.strip() for c in x if c.strip() != ""])
)

In [228]:
cuisine_lists.explode().value_counts()

Cuisine_offered
North Indian      2558
Fast Food         1811
Chinese           1266
Beverages          860
South Indian       469
                  ...
Korean               1
Bubble Tea           1
Awadhi               1
Middle Eastern       1
Hot dogs             1
Name: count, Length: 64, dtype: int64

In [229]:
cuisine_counts = cuisine_lists.explode().value_counts()
cuisine_counts.shape

(64,)

In [230]:
cuisine_counts.head(64)

Cuisine_offered
North Indian      2558
Fast Food         1811
Chinese           1266
Beverages          860
South Indian       469
                  ...
Korean               1
Bubble Tea           1
Awadhi               1
Middle Eastern       1
Hot dogs             1
Name: count, Length: 64, dtype: int64

In [231]:
possible_cuisine_counts = (
    df["Cuisine_offered"]
    .fillna("")
    .str.split(",")
    .explode()
    .str.strip()
    .value_counts()
)

possible_cuisine_counts

Cuisine_offered
North Indian      2558
Fast Food         1811
Chinese           1266
Beverages          860
South Indian       469
                  ...
Korean               1
Bubble Tea           1
Awadhi               1
Middle Eastern       1
Hot dogs             1
Name: count, Length: 65, dtype: int64

In [232]:
cuisine_table = (
    cuisine_counts
    .rename_axis("cuisine")
    .reset_index(name="restaurant_count")
)

cuisine_table

           cuisine  restaurant_count
0     North Indian              2558
1        Fast Food              1811
2          Chinese              1266
3        Beverages               860
4     South Indian               469
..             ...               ...
59          Korean                 1
60      Bubble Tea                 1
61          Awadhi                 1
62  Middle Eastern                 1
63        Hot dogs                 1

[64 rows x 2 columns]

In [233]:
CAFE_TYPE_CUISINES = [
    "Cafe",
    "Beverages",
    "Desserts",
    "Bakery",
    "Coffee",
    "Tea",
]

In [234]:
df["is_explicit_cafe"]=(
    df["category"].str.contains("CAF", case=False , na=False)
)

In [235]:
df["has_cafe_type_cuisine"] = (
    df["Cuisine_offered"]
    .fillna("")
    .str.contains(
        "|".join(CAFE_TYPE_CUISINES),
        case=False,
        na=False
    )
)

In [236]:
df[["is_explicit_cafe", "has_cafe_type_cuisine"]].value_counts()

is_explicit_cafe  has_cafe_type_cuisine
False             False                    3279
                  True                     1210
True              True                      230
                  False                       8
Name: count, dtype: int64

In [237]:
possible_cafes = df[
    (~df["is_explicit_cafe"]) &
    (df["has_cafe_type_cuisine"])
].copy()

In [238]:
possible_cuisine_counts = (
    possible_cafes["Cuisine_offered"]
    .fillna("")
    .str.split(",")
    .explode()
    .str.strip()
    .value_counts()
)

possible_cuisine_counts

Cuisine_offered
Beverages        798
Fast Food        694
Bakery           335
North Indian     318
Chinese          280
Desserts         228
South Indian      92
Street Food       91
Ice Cream         81
Pizza             71
Burger            62
Italian           54
Sandwich          40
Tea               30
Juices            30
Continental       29
Rolls             20
Mughlai           19
Mithai            17
Healthy Food      17
Rajasthani        16
Momos             12
Coffee            11
Cafe              11
Biryani            6
Mexican            5
Asian              5
Salad              5
Kebab              2
Bar Food           2
Wraps              2
Lebanese           2
Hyderabadi         1
Lucknowi           1
American           1
Korean             1
Bubble Tea         1
Frozen Yogurt      1
Finger Food        1
Turkish            1
Name: count, dtype: int64

In [239]:
for cuisine in CAFE_TYPE_CUISINES:
    matches = possible_cafes[
        possible_cafes["Cuisine_offered"]
        .fillna("")
        .str.contains(cuisine, case=False, na=False)
    ]

    print(f"\n--- {cuisine}: {len(matches)} ---")
    print(
        matches[
            ["Name", "category", "Cuisine_offered"]
        ].head(10).to_string(index=False)
    )

--- Cafe: 11 ---
                          Name       category                                     Cuisine_offered
               Coffee Junction   Quick Bites                         Continental, Fast Food, Cafe
                     Cup Tales   Quick Bites                             Cafe, Italian, Beverages
                  Jaipur Pizza            NaN Fast Food, Beverages, Pizza, Burger, Sandwich, Cafe
                      Kafestop   Quick Bites                 Sandwich, Fast Food, Beverages, Cafe
Monkey Momo's - By Bubble Rush   Quick Bites          Cafe, Momos, Bubble Tea, Chinese, Beverages
         Nothing Before Coffee Beverage Shop                                      Cafe, Fast Food
               Oven The Bakery        Bakery                   Cafe, Bakery, Continental, Italian
                PubG Zone Cafe   Quick Bites                                   North Indian, Cafe
              Tea Connect Cafe   Quick Bites              Cafe, Fast Food, Street Food, Beverages
  The CAF� Express - The Lalit Casual Dining                                   South Indian, Cafe

--- Beverages: 798 ---
                      Name            category                                        Cuisine_offered
                 11 Haandi                 NaN                     South Indian, Beverages, Fast Food
           1805 Restaurant        Quick Bites                                 North Indian, Beverages
       3 D's Restro Lounge Casual Dining, Bar  North Indian, Chinese, Italian, Continental, Beverages
                  365 Cafe        Quick Bites                                    Fast Food, Beverages
          3D Restro Lounge        Lounge, Pub    North Indian, Fast Food, Italian, Chinese, Beverages
         72 Singh Ka Dhaba        Quick Bites             Fast Food, Chinese, North Indian, Beverages
                7th Heaven             Bakery                  Bakery, Desserts, Fast Food, Beverages
90 Bata 3 The Desi Canteen        Quick Bites         Street Food, Fast Food, North Indian, Beverages
              A Chai Story        Quick Bites                               Tea, Fast Food, Beverages
           A Little Pantry                 NaN                      North Indian, Beverages, Desserts

--- Desserts: 228 ---
                          Name                     category                        Cuisine_offered
                    7th Heaven                      Bakery  Bakery, Desserts, Fast Food, Beverages
               A Little Pantry                          NaN      North Indian, Beverages, Desserts
Ambika Baker's & Confectioners                      Bakery             Bakery, Fast Food, Desserts
  Anand Bakers & Confectionery                      Bakery             Bakery, Desserts, Fast Food
        Anand Ice-Cream Parlor              Dessert Parlor          Ice Cream, Desserts, Beverages
    Anas Kulfi - Coffee Center               Beverage Shop          Beverages, Desserts, Ice Cream
             Apsara Ice Creams              Dessert Parlor                     Ice Cream, Desserts
          Ashirwad Cake N Bake                          NaN                 Desserts, North Indian
      Belgium's Waffle Station Dessert Parlor, Quick Bites          Desserts, Fast Food, Beverages
      Belgium's Waffle Station Dessert Parlor, Quick Bites          Desserts, Fast Food, Beverages

--- Bakery: 335 ---
                          Name                category                        Cuisine_offered
                    7th Heaven                 Bakery  Bakery, Desserts, Fast Food, Beverages
               Adhinath Bakery    Bakery, Quick Bites            Bakery, Fast Food, Beverages
         Agarwal Bakes & Bites                 Bakery                                  Bakery
              Agarwal Caterers     Sweet Shop, Bakery                          Mithai, Bakery
      Agrawal Pizza And Bakery                     NaN                          Pizza, Bakery
            Aksay Nidhi Bakery    Bakery, Quick Bites                       Bakery, Fast Food
Ambika Baker's & Confectioners                 Bakery             Bakery, Fast Food, Desserts
  Anand Bakers & Confectionery                 Bakery             Bakery, Desserts, Fast Food
Anaye Bakers And Confectionery Bakery, Dessert Parlor            Bakery, Ice Cream, Fast Food
    Angel Bakers And Fast Food                 Bakery                       Bakery, Fast Food

--- Coffee: 11 ---
                              Name                    category                           Cuisine_offered
                     Coffee Corner Beverage Shop, Quick Bites               Coffee, Beverages, Fast Food
              Coffee Statue Circle                Quick Bites               Fast Food, Beverages, Coffee
                       Coffeesthan              Beverage Shop                          Coffee, Beverages
            HOB - House Of Biryani                         NaN Biryani, Chinese, Sandwich, Rolls, Coffee
                         Jain & Co                         NaN             North Indian, Italian, Coffee
        Radhey Shyam Coffee Corner                Quick Bites                          Fast Food, Coffee
Shree Sanwariya Pratha & Tea Stall                Quick Bites                  Tea, Coffee, North Indian
                       Tasty Crush              Beverage Shop                                     Coffee
                 Tea Coffee Snacks Beverage Shop, Quick Bites                     Fast Food, Tea, Coffee
              Tea Tradition Xpress Beverage Shop, Quick Bites                     Tea, Coffee, Fast Food

--- Tea: 31 ---
                   Name                    category                         Cuisine_offered
           A Chai Story                Quick Bites                Tea, Fast Food, Beverages
               Cafe 420                Quick Bites                   Fast Food, Tea, Juices
         Chai Sutta Bar                Quick Bites      Tea, Sandwich, Fast Food, Beverages
         Chai Sutta Bar              Beverage Shop                Tea, Beverages, Fast Food
        Chai Thiya Cafe                Quick Bites       Tea, Beverages, Fast Food, Chinese
               Chai.Com Beverage Shop, Quick Bites  Beverages, Tea, Fast Food, North Indian
              Chaiwalas Quick Bites, Beverage Shop                           Fast Food, Tea
Chuski The Taste Of Tea                Quick Bites                          Tea, Rajasthani
               Cup Of T              Beverage Shop                           Tea, Fast Food
                Cup Tea              Beverage Shop                                      Tea

In [240]:
STRONG_NAME_KEYWORDS = [
    "cafe",
    "coffee",
    "coffeehouse",
    "coffee house",
    "chai cafe",
    "tea cafe",
]

MEDIUM_NAME_KEYWORDS = [
    "chai",
    "tea",
]

In [241]:
name_pattern = "|".join(STRONG_NAME_KEYWORDS)

df["has_cafe_name_signal"] = (
    df["Name"]
    .fillna("")
    .str.contains(name_pattern, case=False, na=False)
)

In [242]:
df[
    [
        "is_explicit_cafe",
        "has_cafe_type_cuisine",
        "has_cafe_name_signal"
    ]
].value_counts()

is_explicit_cafe  has_cafe_type_cuisine  has_cafe_name_signal
False             False                  False                   3125
                  True                   False                   1050
                                         True                     160
                  False                  True                     154
True              True                   True                     132
                                         False                     98
                  False                  False                      4
                                         True                       4
Name: count, dtype: int64

In [243]:
name_only = df[
    (~df["is_explicit_cafe"]) &
    (~df["has_cafe_type_cuisine"]) &
    (df["has_cafe_name_signal"])
].copy()

name_only[["Name", "category", "Cuisine_offered"]].head(30)

,Name,category,Cuisine_offered
24,4 Friends Cafe,Quick Bites,Fast Food
35,999.pt Cafe - Restaurant,Quick Bites,"North Indian, Fast Food"
39,A.D. Cafe,Quick Bites,Fast Food
87,Agarlico Cafe,Quick Bites,Fast Food
103,Airport Cafe,Quick Bites,"North Indian, Fast Food"
134,Amaltas Cafe,Casual Dining,"North Indian, Chinese, Continental"
199,Anokhi Mess & Cafe,Quick Bites,"Fast Food, Street Food"
211,Apna Adda Cafe And Restro,Quick Bites,North Indian
263,Aunty's Cafe,Quick Bites,"North Indian, Chinese, South Indian, Fast Food..."
264,Aunty's Cafe,Casual Dining,"Chinese, North Indian, South Indian"
273,B Bro's Cafe & Restaurant,Quick Bites,"North Indian, Fast Food, Chinese"
284,Be Legend Cafe,Quick Bites,"Healthy Food, Fast Food"
350,Billu's Cafe,Quick Bites,"South Indian, Chinese, Fast Food"
389,BLVR's Corner Cafe & Restaurant,Quick Bites,Fast Food
416,Brew Resto Cafe,Casual Dining,"Chinese, Kebab, North Indian, Italian"
425,Brother's Cafe & Restro,Quick Bites,"North Indian, Chinese, Fast Food"
440,Bunkyard Cafe,Quick Bites,"Fast Food, Chinese, South Indian, North Indian"
498,Cafe 11:11,Casual Dining,"North Indian, Chinese, South Indian, Fast Food"
503,Cafe 666,Quick Bites,"Fast Food, South Indian"
504,Cafe 73,Quick Bites,"Fast Food, Ice Cream"
508,Cafe 99,Casual Dining,"Fast Food, South Indian, North Indian, Chinese"
509,Cafe A2A,Quick Bites,"Fast Food, Chinese, North Indian"
510,Cafe Amer - The Gold Palace & Resorts,Bar,Finger Food
511,Cafe and Garden,Quick Bites,"Fast Food, North Indian"
512,Cafe and Pizza Lounge,Quick Bites,"North Indian, Continental"
513,Cafe and Pizza Lounge,NaN,NaN
514,Cafe Beardo,Quick Bites,"North Indian, Chinese, Fast Food"
530,Cafe Craft,Casual Dining,"Continental, Italian, North Indian"
531,Cafe Cuisine,Quick Bites,"Fast Food, Chinese"
532,Cafe De Kalinga,Quick Bites,"Chinese, South Indian"

In [244]:
name_only = df[
    (df["is_explicit_cafe"]) &
    (~df["has_cafe_type_cuisine"]) &
    (~df["has_cafe_name_signal"])
].copy()

name_only[["Name", "category", "Cuisine_offered"]].head(30)

                  Name    category                         Cuisine_offered
101         Ahimsagram       CAF�                             Healthy Food
758           Chef Box       CAF�   Continental, Italian, Mexican, Chinese
1483  Guru Ji Ki Rasoi  Cafeteria                  North Indian, Fast Food
2239       Laziz Pizza       CAF�                     Italian, Continental

In [245]:
name_only = df[
    (df["is_explicit_cafe"]) &
    (df["has_cafe_type_cuisine"]) &
    (~df["has_cafe_name_signal"])
].copy()

name_only[["Name", "category", "Cuisine_offered"]].head(30)

,Name,category,Cuisine_offered
9,11MG,CAF�,Cafe
31,8 Fumes,CAF�,"Cafe, Fast Food"
42,A2G All Together,"CAF�, Dessert Parlor","Cafe, Desserts, North Indian, Chinese, Frozen ..."
85,After 8,"Lounge, CAF�","Finger Food, Continental, Beverages"
144,Amazing Arena Sports & Lounge,CAF�,"Cafe, Fast Food"
183,Anjum - Fairmont Jaipur,CAF�,Cafe
237,Aromocha,CAF�,"Cafe, Fast Food, Coffee"
260,August House,CAF�,"Cafe, Italian, Fast Food, Continental, Lebanese"
294,Between The Brews,CAF�,"Cafe, North Indian"
370,Bistro Quaint,CAF�,"Cafe, Continental"
377,Black Maple,CAF�,"Cafe, Chinese, North Indian"
401,Bombaye House,"CAF�, Casual Dining","Cafe, Chinese, Street Food, Momos, South India..."
402,Bonana,CAF�,"Cafe, Pizza"
427,Brown Bites,"CAF�, Bakery","Cafe, Bakery"
428,Brown Bites,"CAF�, Bakery","Cafe, Bakery, North Indian"
494,CAF� Bae,"CAF�, Casual Dining","Cafe, Continental, Thai"
495,CAF� Culture Shock,CAF�,"Cafe, Chinese, Fast Food, Beverages"
496,CAF� Indigo,CAF�,Cafe
563,Caffe Cucina,CAF�,"Cafe, Fast Food, North Indian, Beverages"
691,Chai Ho Jaye,CAF�,"Cafe, Fast Food"
693,Chai Republic,CAF�,"Cafe, Fast Food, Beverages"
701,Chaisa,"CAF�, Quick Bites","Cafe, Fast Food, Italian, Beverages"
702,Chaisa,"CAF�, Quick Bites","Cafe, Fast Food, Italian, Beverages"
835,Chool,CAF�,"Cafe, North Indian, Fast Food, South Indian"
885,Coal Quilla,CAF�,Cafe
915,Corner House,"Casual Dining, CAF�","North Indian, Chinese, Italian, Beverages, Ice..."
918,Cosmos Jaipur,CAF�,Cafe
919,Cosmos Jaipur,CAF�,"Cafe, Fast Food"
928,Crazy Craving,"CAF�, Bakery","Cafe, Bakery"
947,Culture,"CAF�, Casual Dining","Cafe, Italian, Chinese, North Indian"

In [246]:
# df["is_cafescope_cafe"] = (
#     df["is_explicit_cafe"] |
#     (
#         ~df["is_explicit_cafe"] |
#         df["has_cafe_name_signal"]
#     )
# )

df["is_cafescope_cafe"] = (
    df["is_explicit_cafe"] |
    df["has_cafe_name_signal"]
)

df["is_cafescope_cafe"].value_counts()

is_cafescope_cafe
False    4175
True      552
Name: count, dtype: int64

In [247]:
# Final CafeScope dataset
cafe_df = df[df["is_cafescope_cafe"]].copy()

print("Original dataset:", len(df))
print("CafeScope dataset:", len(cafe_df))
print("Excluded:", len(df) - len(cafe_df))

Original dataset: 4727
CafeScope dataset: 552
Excluded: 4175

In [248]:
cafe_df = cafe_df.reset_index(drop=True)
cafe_df.head()

,Name,Url,Location,din_rev,del_rev,category,Cuisine_offered,cost_for_two,is_vegeterian,is_bar_available,home_delivery,offers_dining,avg_din_rate,avg_del_rate,is_explicit_cafe,has_cafe_type_cuisine,has_cafe_name_signal,is_cafescope_cafe
0,11MG,https://www.zomato.com/jaipur/11mg-mansarovar,Mansarovar,135 Dining Reviews,837 Delivery Reviews,CAF�,Cafe,400,yes,no,yes,yes,3.8,3.9,True,True,False,True
1,365 Cafe,https://www.zomato.com/jaipur/365-cafe-malviya...,Malviya Nagar,Not enough Dining Reviews,Does not offer Delivery,Quick Bites,"Fast Food, Beverages",400,yes,no,no,yes,NaN,NaN,False,True,True,True
2,4 Friends Cafe,https://www.zomato.com/jaipur/4-friends-cafe-t...,Durgapura,Not enough Dining Reviews,Not enough Delivery Reviews,Quick Bites,Fast Food,150,no,no,yes,yes,NaN,NaN,False,False,True,True
3,8 Fumes,https://www.zomato.com/jaipur/8-fumes-mansarovar,Mansarovar,8 Dining Reviews,Does not offer Delivery,CAF�,"Cafe, Fast Food",400,yes,no,no,yes,2.8,NaN,True,True,False,True
4,999.pt Cafe - Restaurant,https://www.zomato.com/jaipur/999-pt-cafe-rest...,Pratap Nagar,111 Dining Reviews,"2,537 Delivery Reviews",Quick Bites,"North Indian, Fast Food",300,no,no,yes,yes,2.7,2.8,False,False,True,True

In [249]:
cafe_df.columns.tolist()

['Name',
 'Url',
 'Location',
 'din_rev',
 'del_rev',
 'category',
 'Cuisine_offered',
 'cost_for_two',
 'is_vegeterian',
 'is_bar_available',
 'home_delivery',
 'offers_dining',
 'avg_din_rate',
 'avg_del_rate',
 'is_explicit_cafe',
 'has_cafe_type_cuisine',
 'has_cafe_name_signal',
 'is_cafescope_cafe']

In [253]:
cafe_df.shape

(552, 18)

In [250]:
cafe_df.isna().sum().sort_values(ascending=False)

avg_del_rate             310
avg_din_rate             143
category                  28
Cuisine_offered            1
Name                       0
home_delivery              0
has_cafe_name_signal       0
has_cafe_type_cuisine      0
is_explicit_cafe           0
offers_dining              0
is_bar_available           0
Url                        0
is_vegeterian              0
cost_for_two               0
del_rev                    0
din_rev                    0
Location                   0
is_cafescope_cafe          0
dtype: int64

In [251]:
cafe_df.duplicated().sum()

np.int64(0)

In [252]:
cafe_df["Name"].duplicated().sum()

np.int64(32)

In [257]:
output_path = INTERIM_DATA_DIR / "cafe_db.csv"
cafe_df.to_csv(output_path, index=False,encoding='utf-8-sig')