In [1]:
import pandas as pd 
import numpy as np 
from pathlib import Path

In [2]:
PROJECT_ROOT = Path.cwd().parent

RAW_DATA_DIR = PROJECT_ROOT / "data" / "raw"
INTERIM_DATA_DIR = PROJECT_ROOT / "data" / "interim"
PROCESSED_DATA_DIR = PROJECT_ROOT / "data" / "processed"

print("Project root:", PROJECT_ROOT)
print("Raw data:", RAW_DATA_DIR)
print("Interim data:", INTERIM_DATA_DIR)
print("Processed data:", PROCESSED_DATA_DIR)

Project root: /Users/priyashekhawat/Desktop/ree/project/cafescope
Raw data: /Users/priyashekhawat/Desktop/ree/project/cafescope/data/raw
Interim data: /Users/priyashekhawat/Desktop/ree/project/cafescope/data/interim
Processed data: /Users/priyashekhawat/Desktop/ree/project/cafescope/data/processed

In [3]:
input_path = INTERIM_DATA_DIR / "cafe_db.csv"
cafe_db = pd.read_csv(input_path, encoding="utf-8")
cafe_db.head(5)

,Name,Url,Location,din_rev,del_rev,category,Cuisine_offered,cost_for_two,is_vegeterian,is_bar_available,home_delivery,offers_dining,avg_din_rate,avg_del_rate,is_explicit_cafe,has_cafe_type_cuisine,has_cafe_name_signal,is_cafescope_cafe
0,11MG,https://www.zomato.com/jaipur/11mg-mansarovar,Mansarovar,135 Dining Reviews,837 Delivery Reviews,CAF�,Cafe,400,yes,no,yes,yes,3.8,3.9,True,True,False,True
1,365 Cafe,https://www.zomato.com/jaipur/365-cafe-malviya...,Malviya Nagar,Not enough Dining Reviews,Does not offer Delivery,Quick Bites,"Fast Food, Beverages",400,yes,no,no,yes,NaN,NaN,False,True,True,True
2,4 Friends Cafe,https://www.zomato.com/jaipur/4-friends-cafe-t...,Durgapura,Not enough Dining Reviews,Not enough Delivery Reviews,Quick Bites,Fast Food,150,no,no,yes,yes,NaN,NaN,False,False,True,True
3,8 Fumes,https://www.zomato.com/jaipur/8-fumes-mansarovar,Mansarovar,8 Dining Reviews,Does not offer Delivery,CAF�,"Cafe, Fast Food",400,yes,no,no,yes,2.8,NaN,True,True,False,True
4,999.pt Cafe - Restaurant,https://www.zomato.com/jaipur/999-pt-cafe-rest...,Pratap Nagar,111 Dining Reviews,"2,537 Delivery Reviews",Quick Bites,"North Indian, Fast Food",300,no,no,yes,yes,2.7,2.8,False,False,True,True

In [4]:

cafe_db.dtypes

Name                         str
Url                          str
Location                     str
din_rev                      str
del_rev                      str
category                     str
Cuisine_offered              str
cost_for_two                 str
is_vegeterian                str
is_bar_available             str
home_delivery                str
offers_dining                str
avg_din_rate             float64
avg_del_rate             float64
is_explicit_cafe            bool
has_cafe_type_cuisine       bool
has_cafe_name_signal        bool
is_cafescope_cafe           bool
dtype: object

In [5]:
cafe_db.info()

<class 'pandas.DataFrame'>
RangeIndex: 552 entries, 0 to 551
Data columns (total 18 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Name                   552 non-null    str
 1   Url                    552 non-null    str
 2   Location               552 non-null    str
 3   din_rev                552 non-null    str
 4   del_rev                552 non-null    str
 5   category               524 non-null    str
 6   Cuisine_offered        551 non-null    str
 7   cost_for_two           552 non-null    str
 8   is_vegeterian          552 non-null    str
 9   is_bar_available       552 non-null    str
 10  home_delivery          552 non-null    str
 11  offers_dining          552 non-null    str
 12  avg_din_rate           409 non-null    float64
 13  avg_del_rate           242 non-null    float64
 14  is_explicit_cafe       552 non-null    bool
 15  has_cafe_type_cuisine  552 non-null    bool
 16  has_cafe_name_signal   552 non-null    bool
 17  is_cafescope_cafe      552 non-null    bool
dtypes: bool(4), float64(2), str(12)
memory usage: 62.7 KB

In [6]:
cafe_db.columns = (
    cafe_db.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)

In [7]:
cafe_db.columns.tolist()

['name',
 'url',
 'location',
 'din_rev',
 'del_rev',
 'category',
 'cuisine_offered',
 'cost_for_two',
 'is_vegeterian',
 'is_bar_available',
 'home_delivery',
 'offers_dining',
 'avg_din_rate',
 'avg_del_rate',
 'is_explicit_cafe',
 'has_cafe_type_cuisine',
 'has_cafe_name_signal',
 'is_cafescope_cafe']

In [8]:
text_columns = [
    "name",
    "location",
    "category",
    "cuisine_offered"
]

for col in text_columns:
    cafe_db[col] = (
        cafe_db[col]
        .astype("string")
        .str.strip()
    )

In [9]:
cafe_db[text_columns] = cafe_db[text_columns].replace(
    r"^\s*$",
    pd.NA,
    regex=True
)

In [10]:
cafe_db["cost_for_two"].value_counts().head(30)

cost_for_two
400      96
300      80
500      68
200      49
600      47
250      36
350      27
150      24
700      20
800      19
450      16
550      15
100       8
1,200     8
650       6
1,000     6
750       6
850       5
900       5
1,500     3
1,400     2
2,500     1
1,600     1
1,100     1
1,800     1
1,250     1
1,700     1
Name: count, dtype: int64

In [11]:
numeric_columns = [
    "cost_for_two",
    "avg_din_rate",
    "avg_del_rate"
]

cafe_db[numeric_columns].dtypes

cost_for_two        str
avg_din_rate    float64
avg_del_rate    float64
dtype: object

In [12]:
for col in numeric_columns:
    cafe_db[col] = pd.to_numeric(
        cafe_db[col],
        errors="coerce"
    )

In [13]:
cafe_db[numeric_columns].describe()

       cost_for_two  avg_din_rate  avg_del_rate
count    527.000000    409.000000    242.000000
mean     415.654649      3.510024      3.662397
std      179.131561      0.493161      0.412601
min      100.000000      2.000000      2.200000
25%      300.000000      3.200000      3.400000
50%      400.000000      3.500000      3.700000
75%      500.000000      3.800000      3.900000
max      900.000000      4.900000      4.800000

In [14]:
before = len(cafe_db)

cafe_db = cafe_db.drop_duplicates().copy()

after = len(cafe_db)

print("Rows before:", before)
print("Rows after:", after)
print("Exact duplicates removed:", before - after)

Rows before: 552
Rows after: 552
Exact duplicates removed: 0

In [15]:
missing_summary = pd.DataFrame({
    "missing_count": cafe_db.isna().sum(),
    "missing_percent": (
        cafe_db.isna().mean() * 100
    ).round(2)
}).sort_values(
    "missing_count",
    ascending=False
)

missing_summary

                       missing_count  missing_percent
avg_del_rate                     310            56.16
avg_din_rate                     143            25.91
category                          28             5.07
cost_for_two                      25             4.53
cuisine_offered                    1             0.18
name                               0             0.00
offers_dining                      0             0.00
has_cafe_name_signal               0             0.00
has_cafe_type_cuisine              0             0.00
is_explicit_cafe                   0             0.00
is_bar_available                   0             0.00
home_delivery                      0             0.00
url                                0             0.00
is_vegeterian                      0             0.00
del_rev                            0             0.00
din_rev                            0             0.00
location                           0             0.00
is_cafescope_cafe                  0             0.00

In [16]:
print("Final shape:", cafe_db.shape)

print("\nData types:")
print(cafe_db.dtypes)

print("\nExact duplicates:")
print(cafe_db.duplicated().sum())

Final shape: (552, 18)

Data types:
name                      string
url                          str
location                  string
din_rev                      str
del_rev                      str
category                  string
cuisine_offered           string
cost_for_two             float64
is_vegeterian                str
is_bar_available             str
home_delivery                str
offers_dining                str
avg_din_rate             float64
avg_del_rate             float64
is_explicit_cafe            bool
has_cafe_type_cuisine       bool
has_cafe_name_signal        bool
is_cafescope_cafe           bool
dtype: object

Exact duplicates:
0

In [17]:
cafe_db.head(10)

,name,url,location,din_rev,del_rev,category,cuisine_offered,cost_for_two,is_vegeterian,is_bar_available,home_delivery,offers_dining,avg_din_rate,avg_del_rate,is_explicit_cafe,has_cafe_type_cuisine,has_cafe_name_signal,is_cafescope_cafe
0,11MG,https://www.zomato.com/jaipur/11mg-mansarovar,Mansarovar,135 Dining Reviews,837 Delivery Reviews,CAF�,Cafe,400.0,yes,no,yes,yes,3.8,3.9,True,True,False,True
1,365 Cafe,https://www.zomato.com/jaipur/365-cafe-malviya...,Malviya Nagar,Not enough Dining Reviews,Does not offer Delivery,Quick Bites,"Fast Food, Beverages",400.0,yes,no,no,yes,NaN,NaN,False,True,True,True
2,4 Friends Cafe,https://www.zomato.com/jaipur/4-friends-cafe-t...,Durgapura,Not enough Dining Reviews,Not enough Delivery Reviews,Quick Bites,Fast Food,150.0,no,no,yes,yes,NaN,NaN,False,False,True,True
3,8 Fumes,https://www.zomato.com/jaipur/8-fumes-mansarovar,Mansarovar,8 Dining Reviews,Does not offer Delivery,CAF�,"Cafe, Fast Food",400.0,yes,no,no,yes,2.8,NaN,True,True,False,True
4,999.pt Cafe - Restaurant,https://www.zomato.com/jaipur/999-pt-cafe-rest...,Pratap Nagar,111 Dining Reviews,"2,537 Delivery Reviews",Quick Bites,"North Indian, Fast Food",300.0,no,no,yes,yes,2.7,2.8,False,False,True,True
5,A.D. Cafe,https://www.zomato.com/jaipur/a-d-cafe-sodala,Sodala,Not enough Dining Reviews,Does not offer Delivery,Quick Bites,Fast Food,200.0,no,no,no,yes,NaN,NaN,False,False,True,True
6,A2G All Together,https://www.zomato.com/jaipur/a2g-all-together...,Lal Kothi,496 Dining Reviews,"1,089 Delivery Reviews","CAF�, Dessert Parlor","Cafe, Desserts, North Indian, Chinese, Frozen ...",600.0,yes,no,yes,yes,4.0,3.6,True,True,False,True
7,Aapno Cafe,https://www.zomato.com/jaipur/aapno-cafe-ajmer...,Ajmer Highway,12 Dining Reviews,Not enough Delivery Reviews,Quick Bites,"Beverages, Fast Food",250.0,no,no,yes,yes,3.1,NaN,False,True,True,True
8,Affetto Cafe,https://www.zomato.com/jaipur/affetto-cafe-gop...,Gopalbari,154 Dining Reviews,545 Delivery Reviews,Casual Dining,"North Indian, Chinese, Fast Food, Beverages",650.0,no,no,yes,yes,2.8,3.4,False,True,True,True
9,After 8,https://www.zomato.com/jaipur/after-8-sansar-c...,Sansar Chandra Road,Not enough Dining Reviews,Does not offer Delivery,"Lounge, CAF�","Finger Food, Continental, Beverages",NaN,no,yes,no,yes,NaN,NaN,True,True,False,True

In [18]:
flag_columns = [
    "is_vegeterian",
    "is_bar_available",
    "home_delivery",
    "offers_dining"
]

for col in flag_columns:
    print(f"\n--- {col} ---")
    print(cafe_db[col].value_counts(dropna=False))

--- is_vegeterian ---
is_vegeterian
yes    291
no     261
Name: count, dtype: int64

--- is_bar_available ---
is_bar_available
no     542
yes     10
Name: count, dtype: int64

--- home_delivery ---
home_delivery
yes    410
no     142
Name: count, dtype: int64

--- offers_dining ---
offers_dining
yes    511
no      41
Name: count, dtype: int64

In [19]:
flag_columns = [
    "is_vegeterian",
    "is_bar_available",
    "home_delivery",
    "offers_dining"
]

for col in flag_columns:
    cafe_db[col] = (
        cafe_db[col]
        .str.strip()
        .str.lower()
        .map({
            "yes": True,
            "no": False
        })
    )

In [20]:
for col in flag_columns:
    print(cafe_db[col].value_counts(dropna=False))

is_vegeterian
True     291
False    261
Name: count, dtype: int64
is_bar_available
False    542
True      10
Name: count, dtype: int64
home_delivery
True     410
False    142
Name: count, dtype: int64
offers_dining
True     511
False     41
Name: count, dtype: int64

In [21]:
for col in ["din_rev", "del_rev"]:
    print(f"\n--- {col} ---")
    print(cafe_db[col].value_counts(dropna=False).head(20))

--- din_rev ---
din_rev
Not enough Dining Reviews    91
Does not offer Dining        41
4 Dining Reviews             20
8 Dining Reviews             19
5 Dining Reviews             16
7 Dining Reviews             13
10 Dining Reviews            12
6 Dining Reviews             10
12 Dining Reviews             9
14 Dining Reviews             8
17 Dining Reviews             8
15 Dining Reviews             7
9 Dining Reviews              7
40 Dining Reviews             6
22 Dining Reviews             6
13 Dining Reviews             6
25 Dining Reviews             5
26 Dining Reviews             5
11 Dining Reviews             5
57 Dining Reviews             4
Name: count, dtype: int64

--- del_rev ---
del_rev
Not enough Delivery Reviews    160
Does not offer Delivery        142
35 Delivery Reviews              4
42 Delivery Reviews              4
73 Delivery Reviews              3
24 Delivery Reviews              3
1,670 Delivery Reviews           3
23 Delivery Reviews              3
53 Delivery Reviews              3
287 Delivery Reviews             3
55 Delivery Reviews              3
21 Delivery Reviews              3
30 Delivery Reviews              2
214 Delivery Reviews             2
2,058 Delivery Reviews           2
92 Delivery Reviews              2
313 Delivery Reviews             2
56 Delivery Reviews              2
124 Delivery Reviews             2
57 Delivery Reviews              2
Name: count, dtype: int64

In [22]:
cafe_db["dining_review_count"] = (
    cafe_db["din_rev"]
    .str.extract(r"(\d+)")
    [0]
    .astype("Float64")
)

In [23]:
cafe_db[
    ["din_rev", "dining_review_count"]
].head(20)

                      din_rev  dining_review_count
0          135 Dining Reviews                135.0
1   Not enough Dining Reviews                 <NA>
2   Not enough Dining Reviews                 <NA>
3            8 Dining Reviews                  8.0
4          111 Dining Reviews                111.0
5   Not enough Dining Reviews                 <NA>
6          496 Dining Reviews                496.0
7           12 Dining Reviews                 12.0
8          154 Dining Reviews                154.0
9   Not enough Dining Reviews                 <NA>
10          57 Dining Reviews                 57.0
11           7 Dining Reviews                  7.0
12          12 Dining Reviews                 12.0
13          15 Dining Reviews                 15.0
14          79 Dining Reviews                 79.0
15  Not enough Dining Reviews                 <NA>
16          34 Dining Reviews                 34.0
17         684 Dining Reviews                684.0
18  Not enough Dining Reviews                 <NA>
19           4 Dining Reviews                  4.0

In [24]:
cafe_db["delivery_review_count"] = (
    cafe_db["del_rev"]
    .str.extract(r"([\d,]+)")[0]
    .str.replace(",", "", regex=False)
    .astype("Float64")
)

In [25]:
cafe_db[
    ["del_rev", "delivery_review_count"]
].head(20)

                        del_rev  delivery_review_count
0          837 Delivery Reviews                  837.0
1       Does not offer Delivery                   <NA>
2   Not enough Delivery Reviews                   <NA>
3       Does not offer Delivery                   <NA>
4        2,537 Delivery Reviews                 2537.0
5       Does not offer Delivery                   <NA>
6        1,089 Delivery Reviews                 1089.0
7   Not enough Delivery Reviews                   <NA>
8          545 Delivery Reviews                  545.0
9       Does not offer Delivery                   <NA>
10         483 Delivery Reviews                  483.0
11  Not enough Delivery Reviews                   <NA>
12          76 Delivery Reviews                   76.0
13  Not enough Delivery Reviews                   <NA>
14  Not enough Delivery Reviews                   <NA>
15  Not enough Delivery Reviews                   <NA>
16      Does not offer Delivery                   <NA>
17      Does not offer Delivery                   <NA>
18      Does not offer Delivery                   <NA>
19  Not enough Delivery Reviews                   <NA>

In [26]:
cafe_db[
    [
        "dining_review_count",
        "delivery_review_count"
    ]
].describe()

       dining_review_count  delivery_review_count
count                420.0                  250.0
mean            103.954762                724.264
std             171.420571            1211.116718
min                    1.0                   10.0
25%                   10.0                   73.5
50%                   37.0                  233.0
75%                 113.25                 815.25
max                  984.0                 9407.0

In [27]:
cafe_db["category"].value_counts(dropna=False)

category
Quick Bites                      198
CAF�                             189
Casual Dining                     37
<NA>                              28
CAF�, Casual Dining               19
Beverage Shop                     18
CAF�, Bakery                      11
Beverage Shop, Quick Bites         8
Casual Dining, CAF�                6
Bakery                             5
Bakery, Quick Bites                4
Dessert Parlor                     4
CAF�, Dessert Parlor               3
CAF�, Quick Bites                  3
Bakery, CAF�                       3
Quick Bites, Bakery                2
Lounge, CAF�                       1
Beverage Shop, Bakery              1
Bar                                1
Cafeteria                          1
Quick Bites, Fine Dining           1
Quick Bites, CAF�                  1
Quick Bites, Sweet Shop            1
CAF�, CAF�                         1
Quick Bites, Food Court            1
Food Court                         1
Dhaba                              1
Quick Bites, Beverage Shop         1
Food Truck                         1
Beverage Shop, Dessert Parlor      1
Name: count, dtype: Int64

In [28]:
cafe_db["category"] = (
    cafe_db["category"]
    .str.replace("CAF�", "CAFE", regex=False)
    .str.strip()
)

In [29]:
cafe_db["category"].value_counts(dropna=False).head(30)

category
Quick Bites                      198
CAFE                             189
Casual Dining                     37
<NA>                              28
CAFE, Casual Dining               19
Beverage Shop                     18
CAFE, Bakery                      11
Beverage Shop, Quick Bites         8
Casual Dining, CAFE                6
Bakery                             5
Bakery, Quick Bites                4
Dessert Parlor                     4
CAFE, Dessert Parlor               3
CAFE, Quick Bites                  3
Bakery, CAFE                       3
Quick Bites, Bakery                2
Lounge, CAFE                       1
Beverage Shop, Bakery              1
Bar                                1
Cafeteria                          1
Quick Bites, Fine Dining           1
Quick Bites, CAFE                  1
Quick Bites, Sweet Shop            1
CAFE, CAFE                         1
Quick Bites, Food Court            1
Food Court                         1
Dhaba                              1
Quick Bites, Beverage Shop         1
Food Truck                         1
Beverage Shop, Dessert Parlor      1
Name: count, dtype: Int64

In [30]:
cafe_db["location"].value_counts().head(30)

location
Malviya Nagar       67
Mansarovar          66
C Scheme            46
Vaishali Nagar      39
Pratap Nagar        29
Jagatpura           26
Raja Park           25
Jhotwara            22
Lal Kothi           19
Durgapura           18
Gopalpura           18
Vidhyadhar Nagar    17
Sodala              14
Shyam Nagar         12
MI Road             11
Pink City           10
Chitrakoot          10
Sanganer             9
Ajmer Highway        8
Bani Park            8
Sitapur              7
Shastri Nagar        7
Adarsh Nagar         6
Amer Road            5
Civil Lines          5
Khatipura Road       5
Sikar Road           5
Kukas                4
Bais Godam           4
Sindhi Camp          4
Name: count, dtype: Int64

In [31]:
print("Cost range:")
print(cafe_db["cost_for_two"].min(), cafe_db["cost_for_two"].max())

print("\nDining rating range:")
print(cafe_db["avg_din_rate"].min(), cafe_db["avg_din_rate"].max())

print("\nDelivery rating range:")
print(cafe_db["avg_del_rate"].min(), cafe_db["avg_del_rate"].max())

Cost range:
100.0 900.0

Dining rating range:
2.0 4.9

Delivery rating range:
2.2 4.8

In [32]:
text_columns = [
    "name",
    "url",
    "location",
    "din_rev",
    "del_rev",
    "category",
    "cuisine_offered"
]

for col in text_columns:
    cafe_db[col] = (
        cafe_db[col]
        .astype("string")
        .str.strip()
    )

In [33]:
print(cafe_db.dtypes)

name                      string
url                       string
location                  string
din_rev                   string
del_rev                   string
category                  string
cuisine_offered           string
cost_for_two             float64
is_vegeterian               bool
is_bar_available            bool
home_delivery               bool
offers_dining               bool
avg_din_rate             float64
avg_del_rate             float64
is_explicit_cafe            bool
has_cafe_type_cuisine       bool
has_cafe_name_signal        bool
is_cafescope_cafe           bool
dining_review_count      Float64
delivery_review_count    Float64
dtype: object

In [34]:
cafe_db.isna().sum()

name                       0
url                        0
location                   0
din_rev                    0
del_rev                    0
category                  28
cuisine_offered            1
cost_for_two              25
is_vegeterian              0
is_bar_available           0
home_delivery              0
offers_dining              0
avg_din_rate             143
avg_del_rate             310
is_explicit_cafe           0
has_cafe_type_cuisine      0
has_cafe_name_signal       0
is_cafescope_cafe          0
dining_review_count      132
delivery_review_count    302
dtype: int64

In [35]:
cafe_db["category"] = cafe_db["category"].fillna("Unknown")

In [36]:
cafe_db["cuisine_offered"].value_counts(dropna=False).head(30)

cuisine_offered
Cafe                                              34
Cafe, Fast Food                                   33
Fast Food, Beverages                              31
Fast Food                                         27
Beverages, Fast Food                              11
North Indian, Fast Food                           10
North Indian, Chinese, Fast Food                  10
Cafe, Chinese                                     10
Fast Food, Chinese                                 9
Cafe, Fast Food, Beverages                         9
North Indian                                       8
Fast Food, Chinese, Beverages                      8
Cafe, Beverages, Sandwich, Fast Food, Desserts     8
Cafe, Bakery                                       7
North Indian, Fast Food, Beverages                 6
Chinese, Fast Food, Beverages                      6
North Indian, Chinese, Fast Food, Beverages        5
Fast Food, North Indian                            5
North Indian, Chinese                              5
South Indian                                       5
Bakery                                             4
North Indian, Fast Food, Chinese                   4
Bakery, Fast Food                                  4
Cafe, Italian, Continental                         4
Fast Food, Pizza, Beverages                        4
Cafe, Fast Food, Street Food, Beverages            4
Cafe, North Indian                                 3
Cafe, Continental                                  3
Cafe, Chinese, North Indian                        3
Cafe, Fast Food, Chinese                           3
Name: count, dtype: Int64

In [37]:
cafe_db["cuisine_offered"] = (
    cafe_db["cuisine_offered"]
    .fillna("Unknown")
)

In [38]:
missing_summary = pd.DataFrame({
    "missing_count": cafe_db.isna().sum(),
    "missing_percent": (
        cafe_db.isna().mean() * 100
    ).round(2)
}).sort_values(
    "missing_count",
    ascending=False
)

missing_summary

                       missing_count  missing_percent
avg_del_rate                     310            56.16
delivery_review_count            302            54.71
avg_din_rate                     143            25.91
dining_review_count              132            23.91
cost_for_two                      25             4.53
offers_dining                      0             0.00
is_cafescope_cafe                  0             0.00
has_cafe_name_signal               0             0.00
has_cafe_type_cuisine              0             0.00
is_explicit_cafe                   0             0.00
name                               0             0.00
url                                0             0.00
is_bar_available                   0             0.00
is_vegeterian                      0             0.00
cuisine_offered                    0             0.00
category                           0             0.00
del_rev                            0             0.00
din_rev                            0             0.00
location                           0             0.00
home_delivery                      0             0.00

In [39]:
print("Cost for two:")
print(cafe_db["cost_for_two"].describe())

print("\nDining rating:")
print(cafe_db["avg_din_rate"].describe())

print("\nDelivery rating:")
print(cafe_db["avg_del_rate"].describe())

print("\nDining review count:")
print(cafe_db["dining_review_count"].describe())

print("\nDelivery review count:")
print(cafe_db["delivery_review_count"].describe())

Cost for two:
count    527.000000
mean     415.654649
std      179.131561
min      100.000000
25%      300.000000
50%      400.000000
75%      500.000000
max      900.000000
Name: cost_for_two, dtype: float64

Dining rating:
count    409.000000
mean       3.510024
std        0.493161
min        2.000000
25%        3.200000
50%        3.500000
75%        3.800000
max        4.900000
Name: avg_din_rate, dtype: float64

Delivery rating:
count    242.000000
mean       3.662397
std        0.412601
min        2.200000
25%        3.400000
50%        3.700000
75%        3.900000
max        4.800000
Name: avg_del_rate, dtype: float64

Dining review count:
count         420.0
mean     103.954762
std      171.420571
min             1.0
25%            10.0
50%            37.0
75%          113.25
max           984.0
Name: dining_review_count, dtype: Float64

Delivery review count:
count          250.0
mean         724.264
std      1211.116718
min             10.0
25%             73.5
50%            233.0
75%           815.25
max           9407.0
Name: delivery_review_count, dtype: Float64

In [40]:
cafe_db.dtypes

name                      string
url                       string
location                  string
din_rev                   string
del_rev                   string
category                  string
cuisine_offered           string
cost_for_two             float64
is_vegeterian               bool
is_bar_available            bool
home_delivery               bool
offers_dining               bool
avg_din_rate             float64
avg_del_rate             float64
is_explicit_cafe            bool
has_cafe_type_cuisine       bool
has_cafe_name_signal        bool
is_cafescope_cafe           bool
dining_review_count      Float64
delivery_review_count    Float64
dtype: object

In [41]:
cleaned_path = INTERIM_DATA_DIR / "cafe_cleaned.csv"
cafe_db.to_csv(cleaned_path, index=False)
print("Saved cleaned data to:", cleaned_path)

Saved cleaned data to: /Users/priyashekhawat/Desktop/ree/project/cafescope/data/interim/cafe_cleaned.csv